/**
 * Normative result language.
 *
 * These strings are part of the specification, not copy to be improvised on. The whole
 * product claim rests on the difference between "no signal was found" and "this was written
 * by a human", so the sentences that carry that distinction live in one file, are used by
 * both the summary and the cards, and are asserted by tests.
 */

import type { SummaryLabel } from './types.ts';

export const SUMMARY_TEXT: Record<SummaryLabel, { heading: string; body: string }> = {
  'verified-provenance': {
    heading: 'Valid Content Credential',
    body:
      'The inspected image contains a cryptographically valid C2PA credential. This claim ' +
      'applies to the image asset, not automatically to surrounding text.',
  },
  'watermark-evidence': {
    heading: 'Watermark signal detected',
    body:
      'The selected text matches the configured SynthID-text detector with a statistically ' +
      'significant score. This is evidence of generation using a compatible watermark ' +
      'configuration; it is not proof of authorship or of an unedited generation history.',
  },
  'no-supported-signal': {
    heading: 'No supported provenance signal detected',
    body:
      'This result does not establish human authorship. The content may be unwatermarked, too ' +
      'short, edited, transformed, generated by an unsupported system, or created before ' +
      'marking was enabled.',
  },
  indeterminate: {
    heading: 'Not enough evidence',
    body: 'This detector could not produce a meaningful result for the available content.',
  },
};

/** Issuer-specific form of the verified-credential sentence. */
export function verifiedCredentialText(issuer?: string): string {
  const who = issuer ? ` issued by ${issuer}` : '';
  return (
    `The inspected image contains a cryptographically valid C2PA credential${who}. ` +
    'This claim applies to the image asset, not automatically to surrounding text.'
  );
}

export const UNAVAILABLE_HEADING = 'Detector unavailable';
export const UNAVAILABLE_BODY =
  'This provider requires authorized detector access or deployment-specific configuration ' +
  'that is not present in this build.';

/** Shown beneath every inspection, regardless of outcome. */
export const GLOBAL_INTERPRETATION_NOTE =
  'Evidence is not equivalent to authorship. Editing and transformation may alter detectable ' +
  'signals, and absence of a signal is not evidence of human authorship.';
